name: Develop BookSource JSON

on:
  push:
    branches:
      - booksource-dev

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run booksource_combine script
      run: |
        python src/scripts/booksource_combine.py

    - name: Upload booksource JSON
      uses: actions/upload-artifact@v4
      with:
        name: booksource-json-files
        path: src/build/*.json